In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [115]:
df = pd.read_csv('raw_data.csv')
df.head()

            Timestamp          Project Type   Country   Average Size of the Construction Site (m²)    Estimated Project Duration What is the primary source of energy used on your construction site   Average Daily Energy Consumption     Peak Power Demand (kW)     Daily Generator Runtime     Do you meter energy use by equipment (e.g., lighting, HVAC)   What generator sizes do you use on site Diesel Consumption per Week     How often is diesel delivered  Monthly Generator Maintenance Cost? (In your country currency)    Common Generator Issues (Select all that apply)   Have you considered using solar/wind energy on this site Is there space for solar installation Would you consider a hybrid (diesel + solar) system What are your main concerns about renewable systems? (Select all that apply) Do you currently track CO₂ emissions from generator use? Are there sustainability requirements for your project? What factors most influence your power source choice? (Select all that apply) Would you share historical fuel or energy usage data? Would you like to join a pilot study or be contacted for follow up? Please enter your email address.  What is your role in the construction industry
0  6/26/2025 11:24:25  residential building       UAE                           more than 10,000 m²            More than 2 years                                  Diesel generators                                      Less than 50 KWh                 20 - 50 KW          more than 12 hours                                                 No                                        150 - 300 KVA          Less than 500 Liters                           Daily                                             8000.0               High fuel cost and fuel logistics, Frequent ma...                                 No, not interested                                      Not sure                                                 No   High initial cost, Technical complexity, Relia...                                                                           No                                                       No                                                    Cost                                                                            No                                                    No                                               NaN                                 Project Manager
1  6/26/2025 11:24:27  residential building       UAE                           more than 10,000 m²            More than 2 years                                  Diesel generators                                      Less than 50 KWh                 20 - 50 KW          more than 12 hours                                                 No                                        150 - 300 KVA          Less than 500 Liters                           Daily                                             8000.0               High fuel cost and fuel logistics, Frequent ma...                                 No, not interested                          Yes, plenty of space                                                 No                                                 NaN                                                                           No                                                       No                                                    Cost                                                                            No                                                    No                                               NaN                                 Project Manager
2  6/26/2025 11:34:34  residential building       UAE                             5,000 – 10,000 m²                6 – 12 months                                   Grid electricity                                          50 - 200 KWh                 20 - 50 KW                8 - 12 hours                                                Yes                                         50 - 150 KVA             500 - 1000 Liters                2-3 times a week                                                NaN                               High fuel cost and fuel logistics                           Yes, we currently use it                          Yes, plenty of space                                                Yes   High initial cost, Technical complexity, Relia...                                                                           No                                                       No                      Cost, Reliability, Client policies                                                                            No                                                    No                                               NaN                               Planning Engineer
3  6/26/2025 11:37:31   road infrastructure       UAE                           more than 10,000 m²            More than 2 years                            Hybrid (Diesel + Solar)                                     More than 500 KWh           More than 150 KW          more than 12 hours                                                Yes                                       Multiple sizes         More than 2000 Liters                  On demand only                                                NaN                                                             NaN                                 No, not interested                                      Not sure                                              Maybe                                                 NaN                                                            Planning to start                                                 Not Sure                                         Client policies                                                                         Maybe                                                 Maybe                              wainyaanaa@gmail.com                               Planning Engineer
4  6/26/2025 11:43:46  residential building       UAE                             5,000 – 10,000 m²           Less than 6 months                                   Grid electricity                                          50 - 200 KWh                 20 - 50 KW              Not applicable                                                Yes                                       Not applicable                      Not sure                  On demand only                                                NaN                                                             NaN                           No, but we’re open to it                            No space available                                                 No   High initial cost, Reliability and Maintenance...                                                            Planning to start                                     Yes – Client request                                                    Cost                                                                           Yes                                                    No                                               NaN                                   Site Engineer

In [116]:
df = df.drop('Timestamp', axis=1)

In [117]:
df.isnull().sum()

Project Type                                                                      0
  Country                                                                         0
  Average Size of the Construction Site (m²)                                      0
  Estimated Project Duration                                                      0
What is the primary source of energy used on your construction site               0
  Average Daily Energy Consumption                                                0
  Peak Power Demand (kW)                                                          0
  Daily Generator Runtime                                                         0
  Do you meter energy use by equipment (e.g., lighting, HVAC)                     0
  What generator sizes do you use on site                                         0
Diesel Consumption per Week                                                       2
  How often is diesel delivered                                                   3
Monthly Generator Maintenance Cost? (In your country currency)                   19
Common Generator Issues (Select all that apply)                                   4
  Have you considered using solar/wind energy on this site                        0
Is there space for solar installation                                             0
Would you consider a hybrid (diesel + solar) system                               0
What are your main concerns about renewable systems? (Select all that apply)      6
Do you currently track CO₂ emissions from generator use?                          0
Are there sustainability requirements for your project?                           0
What factors most influence your power source choice? (Select all that apply)     0
Would you share historical fuel or energy usage data?                             0
Would you like to join a pilot study or be contacted for follow up?               0
Please enter your email address.                                                 17
 What is your role in the construction industry                                   0
dtype: int64

In [118]:
df.head()

           Project Type   Country   Average Size of the Construction Site (m²)    Estimated Project Duration What is the primary source of energy used on your construction site   Average Daily Energy Consumption     Peak Power Demand (kW)     Daily Generator Runtime     Do you meter energy use by equipment (e.g., lighting, HVAC)   What generator sizes do you use on site Diesel Consumption per Week     How often is diesel delivered  Monthly Generator Maintenance Cost? (In your country currency)    Common Generator Issues (Select all that apply)   Have you considered using solar/wind energy on this site Is there space for solar installation Would you consider a hybrid (diesel + solar) system What are your main concerns about renewable systems? (Select all that apply) Do you currently track CO₂ emissions from generator use? Are there sustainability requirements for your project? What factors most influence your power source choice? (Select all that apply) Would you share historical fuel or energy usage data? Would you like to join a pilot study or be contacted for follow up? Please enter your email address.  What is your role in the construction industry
0  residential building       UAE                           more than 10,000 m²            More than 2 years                                  Diesel generators                                      Less than 50 KWh                 20 - 50 KW          more than 12 hours                                                 No                                        150 - 300 KVA          Less than 500 Liters                           Daily                                             8000.0               High fuel cost and fuel logistics, Frequent ma...                                 No, not interested                                      Not sure                                                 No   High initial cost, Technical complexity, Relia...                                                                           No                                                       No                                                    Cost                                                                            No                                                    No                                               NaN                                 Project Manager
1  residential building       UAE                           more than 10,000 m²            More than 2 years                                  Diesel generators                                      Less than 50 KWh                 20 - 50 KW          more than 12 hours                                                 No                                        150 - 300 KVA          Less than 500 Liters                           Daily                                             8000.0               High fuel cost and fuel logistics, Frequent ma...                                 No, not interested                          Yes, plenty of space                                                 No                                                 NaN                                                                           No                                                       No                                                    Cost                                                                            No                                                    No                                               NaN                                 Project Manager
2  residential building       UAE                             5,000 – 10,000 m²                6 – 12 months                                   Grid electricity                                          50 - 200 KWh                 20 - 50 KW                8 - 12 hours                                                Yes                                         50 - 150 KVA             500 - 1000 Liters                2-3 times a week                                                NaN                               High fuel cost and fuel logistics                           Yes, we currently use it                          Yes, plenty of space                                                Yes   High initial cost, Technical complexity, Relia...                                                                           No                                                       No                      Cost, Reliability, Client policies                                                                            No                                                    No                                               NaN                               Planning Engineer
3   road infrastructure       UAE                           more than 10,000 m²            More than 2 years                            Hybrid (Diesel + Solar)                                     More than 500 KWh           More than 150 KW          more than 12 hours                                                Yes                                       Multiple sizes         More than 2000 Liters                  On demand only                                                NaN                                                             NaN                                 No, not interested                                      Not sure                                              Maybe                                                 NaN                                                            Planning to start                                                 Not Sure                                         Client policies                                                                         Maybe                                                 Maybe                              wainyaanaa@gmail.com                               Planning Engineer
4  residential building       UAE                             5,000 – 10,000 m²           Less than 6 months                                   Grid electricity                                          50 - 200 KWh                 20 - 50 KW              Not applicable                                                Yes                                       Not applicable                      Not sure                  On demand only                                                NaN                                                             NaN                           No, but we’re open to it                            No space available                                                 No   High initial cost, Reliability and Maintenance...                                                            Planning to start                                     Yes – Client request                                                    Cost                                                                           Yes                                                    No                                               NaN                                   Site Engineer

In [119]:
df.shape

(29, 25)

In [120]:
#checking for columns names
df.columns

Index(['Project Type', '  Country',
       '  Average Size of the Construction Site (m²) ',
       '  Estimated Project Duration',
       'What is the primary source of energy used on your construction site',
       '  Average Daily Energy Consumption  ', '  Peak Power Demand (kW)  ',
       '  Daily Generator Runtime  ',
       '  Do you meter energy use by equipment (e.g., lighting, HVAC)',
       '  What generator sizes do you use on site',
       'Diesel Consumption per Week  ', '  How often is diesel delivered',
       'Monthly Generator Maintenance Cost? (In your country currency)',
       'Common Generator Issues (Select all that apply)',
       '  Have you considered using solar/wind energy on this site',
       'Is there space for solar installation',
       'Would you consider a hybrid (diesel + solar) system',
       'What are your main concerns about renewable systems? (Select all that apply)',
       'Do you currently track CO₂ emissions from generator use?',
       'Are there sustainability requirements for your project?',
       'What factors most influence your power source choice? (Select all that apply)',
       'Would you share historical fuel or energy usage data?',
       'Would you like to join a pilot study or be contacted for follow up?',
       'Please enter your email address.',
       ' What is your role in the construction industry'],
      dtype='object')

In [121]:
# Define verbose and final column names
verbose_column_names = [
    ' What is your role in the construction industry', 'Project Type',
    '  Country', '  Average Size of the Construction Site (m²) ',
    '  Estimated Project Duration',
    'What is the primary source of energy used on your construction site',
    '  Average Daily Energy Consumption  ', '  Peak Power Demand (kW)  ',
    '  Daily Generator Runtime  ',
    '  Do you meter energy use by equipment (e.g., lighting, HVAC)',
    '  What generator sizes do you use on site',
    'Diesel Consumption per Week  ', '  How often is diesel delivered',
    'Monthly Generator Maintenance Cost? (In your country currency)',
    'Common Generator Issues (Select all that apply)',
    '  Have you considered using solar/wind energy on this site',
    'Is there space for solar installation',
    'Would you consider a hybrid (diesel + solar) system',
    'What are your main concerns about renewable systems? (Select all that apply)',
    'Do you currently track CO₂ emissions from generator use?',
    'Are there sustainability requirements for your project?',
    'What factors most influence your power source choice? (Select all that apply)',
    'Would you share historical fuel or energy usage data?',
    'Would you like to join a pilot study or be contacted for follow up?',
    'Please enter your email address.'
]

final_column_names = [
    'Industry_Role', 'Project_Type', 'Country', ' Average_Site_Size (m²) ',
    'Project_Duration (Months)', 'Primary_Energy_Source',
    '  Average_Daily_Energy_Consumption (KWh) ', '  Peak_Power_Demand (kW)  ',
    '  Daily_Generator_Runtime  (Hours)', 'Meter_By_Equipment',
    'Generator_Sizes (KVA)', 'Diesel_Consumption_Per_Week (Liters)',
    'Diesel_Delivery_Per_Week', 'Monthly_Gen_Maintenance_Cost',
    'Common_Gen_Issues', 'Considered_Renewables','Space_For_Solar','Consider_Hybrid_System',
    'Renewable_Concerns', 'Track_CO2_Emissions', 'Sustainability_Requirements',
    'Power_Source_Factors','Willing_To_Share_Data',
     'Join_Pilot_Study'
]

# Rename using a dictionary mapping
rename_map = dict(zip(verbose_column_names, final_column_names))
df.rename(columns=rename_map, inplace=True)

In [122]:
#checking for columns names
df.columns

Index(['Project_Type', 'Country', ' Average_Site_Size (m²) ',
       'Project_Duration (Months)', 'Primary_Energy_Source',
       '  Average_Daily_Energy_Consumption (KWh) ',
       '  Peak_Power_Demand (kW)  ', '  Daily_Generator_Runtime  (Hours)',
       'Meter_By_Equipment', 'Generator_Sizes (KVA)',
       'Diesel_Consumption_Per_Week (Liters)', 'Diesel_Delivery_Per_Week',
       'Monthly_Gen_Maintenance_Cost', 'Common_Gen_Issues',
       'Considered_Renewables', 'Space_For_Solar', 'Consider_Hybrid_System',
       'Renewable_Concerns', 'Track_CO2_Emissions',
       'Sustainability_Requirements', 'Power_Source_Factors',
       'Willing_To_Share_Data', 'Join_Pilot_Study',
       'Please enter your email address.', 'Industry_Role'],
      dtype='object')

In [123]:
def clean_column_name(name):
    name = name.strip() # Remove leading/trailing whitespace
    name = name.replace(" (", "(")  # Remove space before (
    name = name.replace("  ", " ")  # Handle double spaces if any
    name = name.replace("Daily_Generator_Runtime (Hours)", "Daily_Generator_Runtime(Hours)")
    return name

# Apply to all column names
df.columns = [clean_column_name(col) for col in df.columns]

df.columns

Index(['Project_Type', 'Country', 'Average_Site_Size(m²)',
       'Project_Duration(Months)', 'Primary_Energy_Source',
       'Average_Daily_Energy_Consumption(KWh)', 'Peak_Power_Demand(kW)',
       'Daily_Generator_Runtime(Hours)', 'Meter_By_Equipment',
       'Generator_Sizes(KVA)', 'Diesel_Consumption_Per_Week(Liters)',
       'Diesel_Delivery_Per_Week', 'Monthly_Gen_Maintenance_Cost',
       'Common_Gen_Issues', 'Considered_Renewables', 'Space_For_Solar',
       'Consider_Hybrid_System', 'Renewable_Concerns', 'Track_CO2_Emissions',
       'Sustainability_Requirements', 'Power_Source_Factors',
       'Willing_To_Share_Data', 'Join_Pilot_Study',
       'Please enter your email address.', 'Industry_Role'],
      dtype='object')

In [124]:
df.shape

(29, 25)

In [125]:
# Ensure all columns show when displaying the DataFrame
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
df.head()

           Project_Type Country Average_Site_Size(m²) Project_Duration(Months)    Primary_Energy_Source Average_Daily_Energy_Consumption(KWh) Peak_Power_Demand(kW) Daily_Generator_Runtime(Hours) Meter_By_Equipment Generator_Sizes(KVA) Diesel_Consumption_Per_Week(Liters) Diesel_Delivery_Per_Week  Monthly_Gen_Maintenance_Cost                                  Common_Gen_Issues     Considered_Renewables       Space_For_Solar Consider_Hybrid_System                                 Renewable_Concerns Track_CO2_Emissions Sustainability_Requirements                Power_Source_Factors Willing_To_Share_Data Join_Pilot_Study Please enter your email address.      Industry_Role
0  residential building     UAE   more than 10,000 m²        More than 2 years        Diesel generators                      Less than 50 KWh            20 - 50 KW             more than 12 hours                 No        150 - 300 KVA                Less than 500 Liters                    Daily                        8000.0  High fuel cost and fuel logistics, Frequent ma...        No, not interested              Not sure                     No  High initial cost, Technical complexity, Relia...                  No                          No                                Cost                    No               No                              NaN    Project Manager
1  residential building     UAE   more than 10,000 m²        More than 2 years        Diesel generators                      Less than 50 KWh            20 - 50 KW             more than 12 hours                 No        150 - 300 KVA                Less than 500 Liters                    Daily                        8000.0  High fuel cost and fuel logistics, Frequent ma...        No, not interested  Yes, plenty of space                     No                                                NaN                  No                          No                                Cost                    No               No                              NaN    Project Manager
2  residential building     UAE     5,000 – 10,000 m²            6 – 12 months         Grid electricity                          50 - 200 KWh            20 - 50 KW                   8 - 12 hours                Yes         50 - 150 KVA                   500 - 1000 Liters         2-3 times a week                           NaN                  High fuel cost and fuel logistics  Yes, we currently use it  Yes, plenty of space                    Yes  High initial cost, Technical complexity, Relia...                  No                          No  Cost, Reliability, Client policies                    No               No                              NaN  Planning Engineer
3   road infrastructure     UAE   more than 10,000 m²        More than 2 years  Hybrid (Diesel + Solar)                     More than 500 KWh      More than 150 KW             more than 12 hours                Yes       Multiple sizes               More than 2000 Liters           On demand only                           NaN                                                NaN        No, not interested              Not sure                  Maybe                                                NaN   Planning to start                    Not Sure                     Client policies                 Maybe            Maybe             wainyaanaa@gmail.com  Planning Engineer
4  residential building     UAE     5,000 – 10,000 m²       Less than 6 months         Grid electricity                          50 - 200 KWh            20 - 50 KW                 Not applicable                Yes       Not applicable                            Not sure           On demand only                           NaN                                                NaN  No, but we’re open to it    No space available                     No  High initial cost, Reliability and Maintenance...   Planning to start        Yes – Client request                                Cost                   Yes               No                              NaN      Site Engineer

In [1]:
# First normalize values by stripping spaces and lowercasing
df['Project_Type'] = df['Project_Type'].str.strip().str.lower()

# Define normalized mapping
project_type_map = {
    'residential building': 'Residential Building',
    'commercial tower': 'Commercial Tower',
    'road infrastructure': 'Infrastructure(Roads)',
    'infrastructure pipelines installation': 'Infrastructure(Pipelines)',
    'classroom with offices': 'Classroom with Offices'
}

# Apply the mapping
df['Project_Type'] = df['Project_Type'].replace(project_type_map)
df['Project_Type'].value_counts()

NameError: name 'df' is not defined

In [ ]:
df['Industry_Role'].value_counts()

In [129]:
df['Country'].value_counts()

Country
UAE              16
Nigeria          11
Saudi Arabia      1
Ghana             1
Name: count, dtype: int64

In [130]:
df["Country"] = df["Country"].str.strip()
df["Country"] = df["Country"].replace("Saudi Arabia", "KSA")
df['Country'].value_counts()

Country
UAE        16
Nigeria    11
KSA         1
Ghana       1
Name: count, dtype: int64

In [131]:
df['Average_Site_Size(m²)'].value_counts()

Average_Site_Size(m²)
more than 10,000 m²    9
1,000 – 5,000 m²       8
5,000 – 10,000 m²      6
less than 1,000 m²     5
Not sure               1
Name: count, dtype: int64

In [132]:
# Mapping descriptive labels to numeric-friendly labels
site_size_map = {
    'more than 10,000 m²': '> 10000',
    '5,000 – 10,000 m²': '5000 - 10000',
    '1,000 – 5,000 m²': '1000 - 5000',
    'less than 1,000 m²': '< 1000'
}

# Apply the mapping
df['Average_Site_Size(m²)'] = df['Average_Site_Size(m²)'].replace(site_size_map)

# Replace "Not sure" with missing value (NaN)
df['Average_Site_Size(m²)'] = df['Average_Site_Size(m²)'].replace('Not sure', np.nan)
df['Average_Site_Size(m²)'].value_counts()

Average_Site_Size(m²)
> 10000         9
1000 - 5000     8
5000 - 10000    6
< 1000          5
Name: count, dtype: int64

In [133]:
df['Project_Duration(Months)'].value_counts()

Project_Duration(Months)
12 – 24 months        9
6 – 12 months         8
More than 2 years     6
Less than 6 months    6
Name: count, dtype: int64

In [134]:
duration_map = {
    'Less than 6 months': '< 6',
    '6 – 12 months': '6 - 12',
    '12 – 24 months': '12 - 24',
    'More than 2 years': '> 24'
}

df['Project_Duration(Months)'] = df['Project_Duration(Months)'].replace(duration_map)
df['Project_Duration(Months)'].value_counts()

Project_Duration(Months)
12 - 24    9
6 - 12     8
> 24       6
< 6        6
Name: count, dtype: int64

In [135]:
df['Primary_Energy_Source'].value_counts()

Primary_Energy_Source
Diesel generators           15
Grid electricity             8
Hybrid (Diesel + Solar)      4
Petrol-engine generator      1
PMS generator                1
Name: count, dtype: int64

In [136]:
df['Primary_Energy_Source'] = df['Primary_Energy_Source'].apply(
    lambda x: x if x in ['Grid electricity', 'Hybrid (Diesel + Solar)'] else 'Generators'
)
df['Primary_Energy_Source'].value_counts()

Primary_Energy_Source
Generators                 17
Grid electricity            8
Hybrid (Diesel + Solar)     4
Name: count, dtype: int64

In [137]:
df['Average_Daily_Energy_Consumption(KWh)'].value_counts()

Average_Daily_Energy_Consumption(KWh)
50 - 200 KWh         12
Less than 50 KWh     11
More than 500 KWh     3
200 - 500 KWh         3
Name: count, dtype: int64

In [138]:
energy_map = {
    'More than 500 KWh': '> 500',
    '50 - 200 KWh': '50 - 200',
    '200 - 500 KWh': '200 - 500',
    'Less than 50 KWh': '< 50'
}

df['Average_Daily_Energy_Consumption(KWh)'] = df['Average_Daily_Energy_Consumption(KWh)'].replace(energy_map)
df['Average_Daily_Energy_Consumption(KWh)'].value_counts()

Average_Daily_Energy_Consumption(KWh)
50 - 200     12
< 50         11
> 500         3
200 - 500     3
Name: count, dtype: int64

In [139]:
df['Peak_Power_Demand(kW)'].value_counts()

Peak_Power_Demand(kW)
20 - 50 KW          15
50 - 150 KW          8
More than 150 KW     3
Less than 20 KW      3
Name: count, dtype: int64

In [140]:
peak_power_map = {
    '50 - 150 KW': '50 - 150',
    '20 - 50 KW': '20 - 50',
    'Less than 20 KW': '< 20',
    'More than 150 KW': '> 150'
}

df['Peak_Power_Demand(kW)'] = df['Peak_Power_Demand(kW)'].replace(peak_power_map)
df['Peak_Power_Demand(kW)'].value_counts()

Peak_Power_Demand(kW)
20 - 50     15
50 - 150     8
> 150        3
< 20         3
Name: count, dtype: int64

In [141]:
df['Meter_By_Equipment'].value_counts()

Meter_By_Equipment
Yes          16
No           10
Partially     3
Name: count, dtype: int64

In [142]:
df['Generator_Sizes(KVA)'].value_counts()

Generator_Sizes(KVA)
150 - 300 KVA        7
50 - 150 KVA         7
Multiple sizes       6
Not applicable       4
Less than 50 KVA     3
More than 300 KVA    2
Name: count, dtype: int64

In [143]:
generator_map = {
    'Less than 50 KVA': '< 50',
    '50 - 150 KVA': '50 - 150',
    '150 - 300 KVA': '150 - 300',
    'More than 300 KVA': '> 300',
    'Multiple sizes': 'Multiple sizes',
    'Not applicable': 'Not applicable'
}

# Apply the mapping safely using .loc
df.loc[:, 'Generator_Sizes(KVA)'] = df['Generator_Sizes(KVA)'].replace(generator_map)
df['Generator_Sizes(KVA)'].value_counts()

Generator_Sizes(KVA)
150 - 300         7
50 - 150          7
Multiple sizes    6
Not applicable    4
< 50              3
> 300             2
Name: count, dtype: int64

In [144]:
runtime_map = {
    'more than 12 hours': '> 12 hours',
    '8 - 12 hours': '8 - 12',
    '4 - 8 hours': '4 - 8',
    'Less than 4 hours': '< 4 hours',
    'Not applicable': 'Not applicable'
}
df.loc[:, 'Daily_Generator_Runtime(Hours)'] = df['Daily_Generator_Runtime(Hours)'].replace(runtime_map)
df['Daily_Generator_Runtime(Hours)'].value_counts()

Daily_Generator_Runtime(Hours)
> 12 hours        7
8 - 12            7
4 - 8             7
Not applicable    4
< 4 hours         4
Name: count, dtype: int64

In [145]:
df['Diesel_Consumption_Per_Week(Liters)'].value_counts()

Diesel_Consumption_Per_Week(Liters)
Less than 500 Liters     13
Not sure                  6
500 - 1000 Liters         5
More than 2000 Liters     2
1000 - 2000 Liters        1
Name: count, dtype: int64

In [146]:
diesel_map = {
    'Less than 500 Liters': '< 500',
    '500 - 1000 Liters': '500 - 1000',
    '1000 - 2000 Liters': '1000 - 2000',
    'More than 2000 Liters': '> 2000',
    'Not sure': 'Not applicable',
}

df.loc[:, 'Diesel_Consumption_Per_Week(Liters)'] = df['Diesel_Consumption_Per_Week(Liters)'].replace(diesel_map)
df['Diesel_Consumption_Per_Week(Liters)'].value_counts()

Diesel_Consumption_Per_Week(Liters)
< 500             13
Not applicable     6
500 - 1000         5
> 2000             2
1000 - 2000        1
Name: count, dtype: int64

In [147]:
df['Diesel_Delivery_Per_Week'].value_counts()

Diesel_Delivery_Per_Week
2-3 times a week    12
On demand only       9
Daily                4
Once a week          1
Name: count, dtype: int64

In [148]:
df['Monthly_Gen_Maintenance_Cost'].value_counts()

Monthly_Gen_Maintenance_Cost
8.000000e+03    2
1.500000e+02    1
1.500000e+03    1
7.000000e+03    1
5.000021e+11    1
1.000000e+05    1
2.000000e+05    1
1.000000e+03    1
0.000000e+00    1
Name: count, dtype: int64

In [149]:
# UAE
df.loc[df["Country"] == "UAE", "Monthly_Gen_Maintenance_Cost"] *= 0.27

# Ghana
df.loc[df["Country"] == "Ghana", "Monthly_Gen_Maintenance_Cost"] *= 0.095

# Nigeria
df.loc[df["Country"] == "Nigeria", "Monthly_Gen_Maintenance_Cost"] *= 0.00065

# Saudi Arabia
df.loc[df["Country"] == "KSA", "Monthly_Gen_Maintenance_Cost"] *= 0.27
df['Monthly_Gen_Maintenance_Cost'].value_counts()

Monthly_Gen_Maintenance_Cost
2.160000e+03    2
4.050000e+01    1
4.050000e+02    1
4.550000e+00    1
3.250014e+08    1
6.500000e+01    1
1.900000e+04    1
2.700000e+02    1
0.000000e+00    1
Name: count, dtype: int64

In [150]:
df['Common_Gen_Issues'].value_counts()

Common_Gen_Issues
High fuel cost and fuel logistics                                          11
High fuel cost and fuel logistics, Frequent maintenance                     6
Frequent maintenance                                                        4
High fuel cost and fuel logistics, Frequent maintenance, Long idle time     2
Long idle time                                                              1
High fuel cost and fuel logistics, Frequent maintenance,                    1
Name: count, dtype: int64

In [151]:
def simplify_gen_issues(text):
    if pd.isna(text):
        return text

    parts = [p.strip() for p in text.split(',')]
    labels = []

    if any("High fuel cost and fuel logistics" in p for p in parts):
        labels.append("Fuel Cost & Logistics")
    if any("Frequent maintenance" in p for p in parts):
        labels.append("Maintenance")
    if any("Long idle time" in p for p in parts):
        labels.append("Idle Time")

    return " + ".join(labels)

# Apply to original column
df['Common_Gen_Issues'] = df['Common_Gen_Issues'].apply(simplify_gen_issues)
df['Common_Gen_Issues'].value_counts()

Common_Gen_Issues
Fuel Cost & Logistics                              11
Fuel Cost & Logistics + Maintenance                 7
Maintenance                                         4
Fuel Cost & Logistics + Maintenance + Idle Time     2
Idle Time                                           1
Name: count, dtype: int64

In [152]:
df['Space_For_Solar'].value_counts()

Space_For_Solar
Yes, plenty of space    11
Limited space           10
No space available       5
Not sure                 3
Name: count, dtype: int64

In [153]:
df['Consider_Hybrid_System'].value_counts()

Consider_Hybrid_System
Yes      15
Maybe     8
No        6
Name: count, dtype: int64

In [154]:
df['Renewable_Concerns'].value_counts()

Renewable_Concerns
High initial cost, Technical complexity, Reliability and Maintenance requirements    5
High initial cost                                                                    5
High initial cost, Reliability and Maintenance requirements                          4
Technical complexity                                                                 4
High initial cost, Technical complexity                                              2
Reliability and Maintenance requirements                                             2
Technical complexity, Reliability and Maintenance requirements                       1
Name: count, dtype: int64

In [155]:
df['Power_Source_Factors'].value_counts()

Power_Source_Factors
Cost                                  10
Cost, Reliability                      6
Reliability                            5
Cost, Reliability, Client policies     4
Cost, Client policies                  2
Client policies                        2
Name: count, dtype: int64

In [156]:
df['Track_CO2_Emissions'].value_counts()

Track_CO2_Emissions
No                   19
Planning to start     5
Yes                   5
Name: count, dtype: int64

In [157]:
df['Sustainability_Requirements'].value_counts()

Sustainability_Requirements
Yes – Government policy    9
Yes – Client request       8
Not Sure                   6
No                         6
Name: count, dtype: int64

In [158]:
df['Considered_Renewables'].value_counts()

Considered_Renewables
No, but we’re open to it        10
No, not interested               7
Yes, we currently use it         6
Yes, but not implemented yet     6
Name: count, dtype: int64

In [160]:
df['Willing_To_Share_Data'].value_counts()

Willing_To_Share_Data
No       12
Yes       9
Maybe     8
Name: count, dtype: int64

In [161]:
df['Join_Pilot_Study'].value_counts()

Join_Pilot_Study
No       11
Yes      10
Maybe     8
Name: count, dtype: int64